# Generated by Django 3.0.8 on 2020-07-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reciter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.IntegerField()),
                ('r_img', models.CharField(max_length=500, verbose_name='تصویر')),
                ('r_folder', models.CharField(max_length=500)),
                ('r_nameAR', models.CharField(max_length=500)),
                ('r_nameEN', models.CharField(max_length=500)),
                ('r_nameFA', models.CharField(max_length=500)),
                ('r_time', models.CharField(blank=True, max_length=500, null=True)),
                ('r_url1', models.CharField(max_length=500)),
                ('r_size1', models.IntegerField()),
                ('r_quality1', models.IntegerField()),
                ('r_url2', models.CharField(blank=True, max_length=500, null=True)),
                ('r_size2', models.IntegerField(blank=True, null=True)),
                ('r_quality2', models.IntegerField(blank=True, null=True)),
                ('r_url3', models.CharField(blank=True, max_length=500, null=True)),
                ('r_size3', models.IntegerField(blank=True, null=True)),
                ('r_quality3', models.IntegerField(blank=True, null=True)),
                ('r_withBesm', models.IntegerField(blank=True, null=True)),
                ('r_type', models.IntegerField(blank=True, choices=[(-1, 'Deleted'), (1, 'Show'), (2, 'Translate'), (3, 'Tafsir'), (4, 'WORD')], default=1, null=True)),
                ('r_ord', models.IntegerField(blank=True, null=True)),
                ('r_mode', models.IntegerField(blank=True, choices=[(-1, 'Translate'), (0, 'Tartil'), (1, 'Mojawad'), (2, 'Moalem'), (3, 'Tahdir'), (4, 'WORD')], default=0, null=True)),
                ('r_create', models.DateTimeField(auto_now_add=True)),
                ('r_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReciterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.IntegerField(blank=True, choices=[(-1, 'Translate'), (0, 'Tartil'), (1, 'Mojawad'), (2, 'Moalem'), (3, 'Tahdir'), (4, 'WORD')], default=0, null=True)),
            ],
        ),
    ]
