# Generated by Django 3.0.8 on 2020-07-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reciter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.IntegerField()),
                ('r_img', models.CharField(max_length=500)),
                ('r_folder', models.CharField(max_length=500)),
                ('r_nameAR', models.CharField(max_length=500)),
                ('r_nameEN', models.CharField(max_length=500)),
                ('r_nameFA', models.CharField(max_length=500)),
                ('r_time', models.CharField(max_length=500)),
                ('r_url1', models.CharField(max_length=500)),
                ('r_size1', models.IntegerField()),
                ('r_quality1', models.IntegerField()),
                ('r_url2', models.CharField(max_length=500)),
                ('r_size2', models.IntegerField()),
                ('r_quality2', models.IntegerField()),
                ('r_url3', models.CharField(max_length=500)),
                ('r_size3', models.IntegerField()),
                ('r_quality3', models.IntegerField()),
                ('r_withBesm', models.IntegerField()),
                ('r_type', models.IntegerField()),
                ('r_ord', models.IntegerField()),
                ('r_mode', models.IntegerField()),
            ],
        ),
    ]
