# Generated by Django 3.0.8 on 2020-07-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciter',
            name='r_create',
        ),
        migrations.RemoveField(
            model_name='reciter',
            name='r_update',
        ),
    ]
