# Generated by Django 3.0.8 on 2020-07-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciter',
            name='r_mode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reciter',
            name='r_ord',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reciter',
            name='r_quality2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reciter',
            name='r_quality3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reciter',
            name='r_size2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reciter',
            name='r_size3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reciter',
            name='r_time',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reciter',
            name='r_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reciter',
            name='r_url2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reciter',
            name='r_url3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reciter',
            name='r_withBesm',
            field=models.IntegerField(null=True),
        ),
    ]
