# Generated by Django 3.0.8 on 2020-07-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_auto_20200714_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciter',
            name='r_mode',
            field=models.IntegerField(choices=[(-1, 'Translate'), (0, 'Tartil'), (1, 'Mojawad'), (2, 'Moalem'), (3, 'Tahdir'), (4, 'WORD')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reciter',
            name='r_type',
            field=models.IntegerField(choices=[(-1, 'Deleted'), (1, 'Show'), (2, 'Translate'), (3, 'Tafsir'), (4, 'WORD')], default=1, null=True),
        ),
    ]
