# Generated by Django 3.0.8 on 2020-07-27 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0002_auto_20200727_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciter',
            name='r_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reciter',
            name='r_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
