# Generated by Django 3.0.8 on 2020-07-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0003_auto_20200727_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='TafTar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'MTarjomeTitles'), (2, 'MTarjome_GID'), (3, 'MTarjomeNames'), (4, 'MTafsirNames'), (4, 'MTafsirTitles'), (4, 'MTafsirVer')])),
                ('mode', models.IntegerField(choices=[(-1, 'Disable'), (1, 'Enable')], default=1)),
                ('text', models.CharField(max_length=500)),
                ('order', models.IntegerField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reciter',
            name='r_type',
            field=models.IntegerField(blank=True, choices=[(-1, 'Disable'), (1, 'Quran'), (2, 'Translate'), (3, 'Tafsir'), (4, 'WORD')], default=1, null=True),
        ),
    ]
