# Generated by Django 3.0.8 on 2020-07-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0004_auto_20200729_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taftar',
            old_name='text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='taftar',
            name='db_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taftar',
            name='reciter_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='taftar',
            name='version',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='taftar',
            name='type',
            field=models.IntegerField(choices=[(1, 'Tarjome'), (2, 'Tafsir')]),
        ),
    ]
