# Generated by Django 3.0.8 on 2020-07-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0005_auto_20200729_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taftar',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='taftar',
            name='version',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
