# Generated by Django 3.0.8 on 2020-07-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0006_auto_20200729_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taftar',
            name='reciter_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
