# Generated by Django 3.0.8 on 2020-08-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0007_auto_20200729_1252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReciterType',
        ),
    ]
