# Generated by Django 3.0.8 on 2020-08-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0009_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taftar',
            name='title',
        ),
        migrations.AddField(
            model_name='taftar',
            name='titleAR',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='taftar',
            name='titleEN',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='taftar',
            name='titleFA',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
